// Mocks generated by Mockito 5.4.4 from annotations
// in convo_test/test/unit/domain_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:convo_test/data/datasources/local/report_local_datasource.dart'
    as _i3;
import 'package:convo_test/data/datasources/remote/report_remote_datasource.dart'
    as _i2;
import 'package:convo_test/data/repositories/report_repository_impl.dart'
    as _i5;
import 'package:convo_test/domain/entities/report_entity.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRemoteReportDataSource_0 extends _i1.SmartFake
    implements _i2.RemoteReportDataSource {
  _FakeRemoteReportDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocalReportDataSource_1 extends _i1.SmartFake
    implements _i3.LocalReportDataSource {
  _FakeLocalReportDataSource_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReport_2 extends _i1.SmartFake implements _i4.Report {
  _FakeReport_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ReportRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportRepositoryImpl extends _i1.Mock
    implements _i5.ReportRepositoryImpl {
  MockReportRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RemoteReportDataSource get remoteDataSource => (super.noSuchMethod(
        Invocation.getter(#remoteDataSource),
        returnValue: _FakeRemoteReportDataSource_0(
          this,
          Invocation.getter(#remoteDataSource),
        ),
      ) as _i2.RemoteReportDataSource);

  @override
  _i3.LocalReportDataSource get localDataSource => (super.noSuchMethod(
        Invocation.getter(#localDataSource),
        returnValue: _FakeLocalReportDataSource_1(
          this,
          Invocation.getter(#localDataSource),
        ),
      ) as _i3.LocalReportDataSource);

  @override
  _i6.Future<_i4.Report> getReport(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReport,
          [
            latitude,
            longitude,
          ],
        ),
        returnValue: _i6.Future<_i4.Report>.value(_FakeReport_2(
          this,
          Invocation.method(
            #getReport,
            [
              latitude,
              longitude,
            ],
          ),
        )),
      ) as _i6.Future<_i4.Report>);
}
