// Mocks generated by Mockito 5.4.4 from annotations
// in convo_test/test/unit/report_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:convo_test/data/datasources/local/report_local_datasource.dart'
    as _i5;
import 'package:convo_test/data/datasources/remote/report_remote_datasource.dart'
    as _i3;
import 'package:convo_test/domain/entities/report_entity.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeReport_0 extends _i1.SmartFake implements _i2.Report {
  _FakeReport_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteReportDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteReportDataSource extends _i1.Mock
    implements _i3.RemoteReportDataSource {
  MockRemoteReportDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Report> fetchReport(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchReport,
          [
            latitude,
            longitude,
          ],
        ),
        returnValue: _i4.Future<_i2.Report>.value(_FakeReport_0(
          this,
          Invocation.method(
            #fetchReport,
            [
              latitude,
              longitude,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Report>);
}

/// A class which mocks [LocalReportDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalReportDataSource extends _i1.Mock
    implements _i5.LocalReportDataSource {
  MockLocalReportDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Report?> getReportFromCache(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReportFromCache,
          [
            latitude,
            longitude,
          ],
        ),
        returnValue: _i4.Future<_i2.Report?>.value(),
      ) as _i4.Future<_i2.Report?>);

  @override
  _i4.Future<void> cacheReport(
    double? latitude,
    double? longitude,
    _i2.Report? report,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheReport,
          [
            latitude,
            longitude,
            report,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
